export const SET_PROMO_CODE = 'SET_PROMO_CODE';
export const SET_PACKAGE_PROMOCODE = 'SET_PACKAGE_PROMOCODE';
export const CLEAR_PROMO_CODE = 'CLEAR_PROMO_CODE';
export const CLEAR_PACKAGE_PROMO_CODE = 'CLEAR_PACKAGE_PROMO_CODE';
export const PROMO_TYPE_FREE_CLASS = 'FREE_CLASS';
export const PROMO_TYPE_PERCENT_OFF_ONE_CLASS = 'PERCENT_OFF';
export const PROMO_TYPE_CASH_OFF = 'CASH_OFF';
export const PROMO_TYPE_GIFT_CARD = 'GIFT_CARD';
export const PROMO_PRODUCT_CLASS = 'CLASS';
export const PROMO_PRODUCT_PACKAGE = 'PACKAGE';
export const PROMO_PRODUCT_UNIVERSAL = 'UNIVERSAL';
export const PROMO_TYPE_ADD_CREDITS = 'ADD_CREDITS';
export const PROMO_TYPE_FIXED = 'FIXED_PRICE';

