export const SET_FILTER = 'SET_FILTER';
export const CLEAR_ALL_FILTERS = 'CLEAR_ALL_FILTERS';
export const RESET_INITIAL_FILTERS = 'RESET_INITIAL_FILTERS';
export const TOGGLE_CLASS_NAME = 'TOGGLE_CLASS_NAME';
export const SET_ALL_FILTERS = 'SET_ALL_FILTERS';
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const SET_SELECTABLE_CLASSNAMES = 'SET_SELECTABLE_CLASSNAMES';
export const SET_SELECTABLE_INSTRUCTORS = 'SET_SELECTABLE_INSTRUCTORS';

